# User config
author: "Hanbyeol Lee"
tagline: "Interaction Design Portfolio"
description: "Hello, I’m Hanbyeol Lee. I’m a Design Researcher specialized in tangible Human-Computer Interaction."
keywords: "Interaction Design, HCI"
email: "hanby.ixd@gmail.com"
cv: "https://drive.google.com/file/d/1hblicyk7J2ZUkZiH7Uc7gSLveIWqRHih/view?usp=sharing"
scholar: "https://scholar.google.com/citations?user=J2aMC2gAAAAJ&hl=ko"
studylog: "https://hanby-ixd.tistory.com"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
