# User config
author: "Hanbyeol Lee"
tagline: "Interaction Design Portfolio"
description: "Hello, I’m Hanbyeol Lee. I’m an interaction designer specialized in tangible Human-Computer Interaction."
keywords: "Interaction Desingn, HCI"
email: "hanby.ixd@gmail.com"
CV: "https://drive.google.com/file/d/1RdR2Nh0c5Nks0kQ-mTPo1lLvKtNJn13P/view?usp=sharing"
scholar: "https://scholar.google.com/citations?user=J2aMC2gAAAAJ&hl=ko"
linkedin: "https://www.linkedin.com/in/hanbyeol-lee-2a3a01108/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
